version: '3'
services:
  web:
    env_file:
      - .env

    build: .

    restart: unless-stopped
    
    volumes:
      - .:/workspace
      - ./:/usr/src/app
      - ~/.ssh:/root/.ssh

    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - backend
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - backend
  
networks:
  backend: